name: Build and Deploy Site

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the site
        run: |
          echo "Building site from root directory..."
          # Add any build commands if needed

      - name: Run update script
        run: node script.js
        env:
          GITHUB_PAT: ${{ secrets.PAT }}

      - name: Commit and push changes to main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Automated update via GitHub Actions" || echo "No changes to commit"
          git push origin main
