name: Update CSV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run update script
        run: node script.js
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
